#+TITLE: Biography
#+DESCRIPTION: A brief overview of my background and interests.
#+TAGS: code html
#+TIME: 4
#+FEATURED: false
#+TIMESTAMP: 2024-12-18T02:39:03+00:00
#+FILENAME: html-intro



* Venkatesh Choppella

Venkatesh Choppella is Associate Professor at the Software
Engineering Research Centre and Associate Dean at the at the
Division of Flexible Learning at the International Institute
of Information Technology Hyderabad, India.

Venkatesh holds a PhD. degree in Computer Science from
Indiana University, Bloomington, USA, and Bachelors and
Masters degrees from the Indian Institutes of Technology,
Kanpur and Madras, respectively. He has held research and
engineering positions in Hewlett Packard, Xerox Palo Alto
Research Centre, Oak Ridge National Laboratory, and the Ohio
State University in the United States.

Venkatesh's current primary research interests are broadly
in Formal Methods for Software Systems and Computer Science
Education Research.

He has published over 85 research papers and technical
reports in the areas of programming languages, formal
methods, compilers, software engineering, and computing
education.
